### Obtener todos los hashtags
GET http://localhost:9999/hashtag

### Obtener hashtag por ID
GET http://localhost:9999/hashtag/1

### Obtener fotos de hashtag
GET http://localhost:9999/hashtag/obtener-fotos/curico

### Obtener fotos de que coincidan por más de un hashtag (debe cumplirlos todos)
GET http://localhost:9999/hashtag/obtener-fotos-por-mas-de-un-hashtag/curico,colocolo

### Crear un nuevo hashtag
POST http://localhost:9999/hashtag
Content-Type: application/json

{
  "etiqueta": "nuevo1"
}


### Actualizar un hashtag
PUT http://localhost:9999/hashtag/1
Content-Type: application/json

{
  "etiqueta": "nuevo2"
}

### Eliminar un hashtag
DELETE http://localhost:9999/hashtag/1